manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp_zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: mcux-sdk-examples
    revision: MCUX_2.16.100_RC1
    path: examples
  - name: FreeRTOS-Kernel
    revision: 4fe54c5f639770ce271dd3693a5cd5475969ae67
    path: rtos/freertos/freertos-kernel
  - name: mcux-sdk-middleware-sdmmc
    revision: 40283d30576ff0c8870f83a2b3c9c052740884c8
    path: middleware/sdmmc
  - name: mcux-sdk-middleware-multicore
    path: middleware/multicore
    revision: 0b7708aff16c1282db3c44eda6704c07e68dbbac
  - name: rpmsg-lite
    path: middleware/multicore/rpmsg_lite
    revision: 2061eae841cab003d4448061cca9ad3969a6a956
  - name: erpc
    path: middleware/multicore/erpc
    url: https://github.com/EmbeddedRPC/erpc
    revision: 5c2c6b76cf29ac124aa6a4f4cff6fae89f988983
  - name: mcux-soc-svd
    revision: MCUX_2.16.100_RC1
    path: svd
  - name: fatfs
    path: middleware/fatfs
    revision: MCUX_2.16.100_RC1
  - name: mcux-sdk-middleware-eiq
    revision: 0bbdcac476d72d6c391ac4b0243df23ae89766a3
    path: middleware/eiq
  - name: mcux-sdk-middleware-deepviewrt
    revision: MCUX_2.13.1
    path: middleware/eiq/deepviewrt
  - name: mcux-sdk-middleware-glow
    revision: MCUX_2.15.000
    path: middleware/eiq/glow
  - name: mcux-sdk-middleware-tensorflow
    revision: MCUX_2.16.100_RC1
    path: middleware/eiq/tensorflow-lite
  - name: mcux-sdk-middleware-usb
    path: middleware/usb
    revision: MCUX_2.16.100_RC1
  - name: mcux-sdk-middleware-edgefast-bluetooth
    path: middleware/edgefast_bluetooth
    revision: 38d1aad3f9195f2e57005cc1b7ac6988fa750336
  - name: mcux-sdk-middleware-ethermind
    path: middleware/wireless/ethermind
    revision: MCUX_2.16.100_RC1
    remote: nxp
  - name: azure-rtos
    path: rtos/azure-rtos
    revision: 7348f5d379ea0adaf363a3d6ab234ebcf84eb7f0
    remote: nxp
  - name: threadx
    path: rtos/azure-rtos/threadx
    revision: 20cc14c1e39db4e4a92cee6eea5f6ad4eb904219
    remote: nxp
  - name: filex
    path: rtos/azure-rtos/filex
    revision: 72b1d883d6e61b090b7148aead305ed23a17dd13
    remote: nxp
  - name: levelx
    path: rtos/azure-rtos/levelx
    revision: e79d22d5a6213313de83412c81e00b95a90d424a
    remote: nxp
  - name: netxduo
    path: rtos/azure-rtos/netxduo
    revision: f3b1d978453a08f1e9de1e14b17f07801776d1c2
    remote: nxp
  - name: usbx
    path: rtos/azure-rtos/usbx
    revision: c2e2c213f8dbf4dd13dcaf3ffa9ee9b29c6ef04f
    remote: nxp
  - name: guix
    path: rtos/azure-rtos/guix
    revision: a4ad6823bae292f0ab012eb3076093b7b1e03c26
    remote: nxp
  - name: mbedtls
    path: middleware/mbedtls
    revision: f51f6ace3f156c43c54b56dd90c2e92e9413c074
  - name: wifi_nxp
    path: middleware/wifi_nxp
    revision: MCUX_2.16.100_RC1
    remote: nxp
  - name: lwip
    path: middleware/lwip
    revision: MCUX_2.16.100_RC1
  - name: littlefs
    path: middleware/littlefs
    revision: 37158b252a0d5da7bdd5a1d1278f56b20d469717
  - name: maestro
    path: middleware/maestro
    revision: 88b02a991199f99fffa19ea3238d21617b917f16
  - name: mcuboot
    path: middleware/mcuboot_opensource
    revision: MCUX_2.16.100_RC1
    remote: nxp_zephyr
  - name: CMSIS_5
    path: core/CMSIS
    revision: ace291fb56654b2a62b4a80cbba8a75abb36aa18
  - name: EAP
    path: middleware/EAP
    revision: MCUX_2.14.0
  - name: VIT
    path: middleware/vit
    revision: d23d588bf6cec259e3654a0efcde35cf3f4b1cb0
  - name: VoiceSeeker
    path: middleware/voice_seeker
    revision: 056d650e60482db5f8a8455050bd3af1ac9bb0ea
  - name: NatureDSP
    path: middleware/dsp
    revision: MCUX_2.16.000
  - name: wpa_supplicant-rtos
    path: middleware/wireless/wpa_supplicant-rtos
    revision: MCUX_2.16.100_RC1
  - name: mcux-sdk-middleware-connectivity-framework
    path: middleware/wireless/framework
    revision: MCUX_2.16.100_RC1
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-controller
    revision: MCUX_2.16.100_RC1
    path: middleware/wireless/ble_controller
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-host
    revision: MCUX_2.16.100_RC1
    path: middleware/wireless/bluetooth
    remote: nxp
  - name: mcux-sdk-middleware-ieee_802.15.4
    revision: 407d9756b561a3e9ef445252d3aed81e9ff9ba10
    path: middleware/wireless/ieee-802.15.4
    remote: nxp
  - name: mcux-sdk-middleware-zigbee
    revision: MCUX_2.16.100_RC1
    path: middleware/wireless/zigbee
    remote: nxp-mcuxpresso
  - name: mcux-secure-subsystem
    revision: 24e5dcd941fcc21456b2fdfabe828ee22d642bad
    path: middleware/secure-subsystem
    remote: nxp-mcuxpresso
  - name: mcux-sdk-middleware-xcvr
    revision: 98bd94fd88b02ecba495d0783b4ce71e2229bdbc
    path: middleware/wireless/XCVR
    remote: nxp-mcuxpresso
  - name: coex
    revision: MCUX_2.16.100_RC1
    path: middleware/wireless/coex
    remote: nxp-mcuxpresso
  self:
    path: core
